package com.ktds.isc.vaadin.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class MyComp extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout	mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel	horizontalSplitPanel_1;
	@AutoGenerated
	private ComboBox	comboBox_1;
	@AutoGenerated
	private GridLayout	gridLayout_3;
	@AutoGenerated
	private TextField	textField_10;
	@AutoGenerated
	private Label	label_8;
	@AutoGenerated
	private TextField	textField_9;
	@AutoGenerated
	private Label	label_6;
	@AutoGenerated
	private TextField	textField_8;
	@AutoGenerated
	private Label	label_7;
	@AutoGenerated
	private TextField	textField_5;
	@AutoGenerated
	private Label	label_5;
	@AutoGenerated
	private TextField	textField_6;
	@AutoGenerated
	private Label	label_3;
	@AutoGenerated
	private TextField	textField_1;
	@AutoGenerated
	private Label	label_4;
	@AutoGenerated
	private TextField	textField_4;
	@AutoGenerated
	private Label	label_2;
	@AutoGenerated
	private TextField	textField_3;
	@AutoGenerated
	private Label	label_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MyComp() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@SuppressWarnings("deprecation")
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalSplitPanel_1
		horizontalSplitPanel_1 = buildHorizontalSplitPanel_1();
		mainLayout.addComponent(horizontalSplitPanel_1, "top:20.0px;left:20.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_1() {
		// common part: create layout
		horizontalSplitPanel_1 = new HorizontalSplitPanel();
		horizontalSplitPanel_1.setImmediate(false);
		horizontalSplitPanel_1.setWidth("920px");
		horizontalSplitPanel_1.setHeight("500px");
		
		// gridLayout_3
		gridLayout_3 = buildGridLayout_3();
		horizontalSplitPanel_1.addComponent(gridLayout_3);
		
		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("-1px");
		comboBox_1.setHeight("-1px");
		horizontalSplitPanel_1.addComponent(comboBox_1);
		
		return horizontalSplitPanel_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_3() {
		// common part: create layout
		gridLayout_3 = new GridLayout();
		gridLayout_3.setImmediate(false);
		gridLayout_3.setWidth("100.0%");
		gridLayout_3.setHeight("-1px");
		gridLayout_3.setMargin(false);
		gridLayout_3.setColumns(3);
		gridLayout_3.setRows(10);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Label");
		gridLayout_3.addComponent(label_1, 0, 0);
		
		// textField_3
		textField_3 = new TextField();
		textField_3.setImmediate(false);
		textField_3.setWidth("-1px");
		textField_3.setHeight("-1px");
		gridLayout_3.addComponent(textField_3, 2, 0);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Label");
		gridLayout_3.addComponent(label_2, 0, 1);
		
		// textField_4
		textField_4 = new TextField();
		textField_4.setImmediate(false);
		textField_4.setWidth("-1px");
		textField_4.setHeight("-1px");
		gridLayout_3.addComponent(textField_4, 2, 1);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Label");
		gridLayout_3.addComponent(label_4, 0, 2);
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		gridLayout_3.addComponent(textField_1, 2, 2);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Label");
		gridLayout_3.addComponent(label_3, 0, 3);
		
		// textField_6
		textField_6 = new TextField();
		textField_6.setImmediate(false);
		textField_6.setWidth("-1px");
		textField_6.setHeight("-1px");
		gridLayout_3.addComponent(textField_6, 2, 3);
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Label");
		gridLayout_3.addComponent(label_5, 0, 4);
		
		// textField_5
		textField_5 = new TextField();
		textField_5.setImmediate(false);
		textField_5.setWidth("-1px");
		textField_5.setHeight("-1px");
		gridLayout_3.addComponent(textField_5, 2, 4);
		
		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("Label");
		gridLayout_3.addComponent(label_7, 0, 5);
		
		// textField_8
		textField_8 = new TextField();
		textField_8.setImmediate(false);
		textField_8.setWidth("-1px");
		textField_8.setHeight("-1px");
		gridLayout_3.addComponent(textField_8, 2, 5);
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Label");
		gridLayout_3.addComponent(label_6, 0, 7);
		
		// textField_9
		textField_9 = new TextField();
		textField_9.setImmediate(false);
		textField_9.setWidth("-1px");
		textField_9.setHeight("-1px");
		gridLayout_3.addComponent(textField_9, 2, 7);
		
		// label_8
		label_8 = new Label();
		label_8.setImmediate(false);
		label_8.setWidth("-1px");
		label_8.setHeight("-1px");
		label_8.setValue("Label");
		gridLayout_3.addComponent(label_8, 0, 8);
		
		// textField_10
		textField_10 = new TextField();
		textField_10.setImmediate(false);
		textField_10.setWidth("-1px");
		textField_10.setHeight("-1px");
		gridLayout_3.addComponent(textField_10, 2, 8);
		
		return gridLayout_3;
	}
}
