/*
 * File: app/model/CustomerData.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Express.model.CustomerData', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            mapping: 'customernumber',
            name: 'customernumber',
            type: 'int'
        },
        {
            mapping: 'customername',
            name: 'customername',
            type: 'string'
        },
        {
            mapping: 'phone',
            name: 'phone',
            type: 'string'
        },
        {
            mapping: 'addressline1',
            name: 'addressline1',
            type: 'string'
        },
        {
            mapping: 'city',
            name: 'city',
            type: 'string'
        },
        {
            mapping: 'state',
            name: 'state',
            type: 'string'
        },
        {
            mapping: 'country',
            name: 'country',
            type: 'string'
        },
        {
            mapping: 'creditlimit',
            name: 'creditlimit',
            type: 'int',
            useNull: true
        },
        {
            mapping: 'employees.employeenumber',
            name: 'employeenumber',
            type: 'int',
            useNull: true
        },
        {
            mapping: 'employees.firstname',
            name: 'firstname',
            type: 'string'
        }
    ]
});