/*
 * File: app/view/CustomerManagement/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Express.view.CustomerManagement.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Paging',
        'Ext.grid.plugin.RowEditing',
        'Ext.form.FieldSet',
        'Ext.form.FieldContainer',
        'Ext.XTemplate'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 60,
                    maxHeight: 60,
                    minHeight: 60,
                    header: false,
                    title: 'My Panel'
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    width: 150,
                    layout: 'accordion',
                    title: 'My Panel'
                },
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    border: 0,
                    itemId: 'contentPanel',
                    maxWidth: 1100,
                    minWidth: 1100,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'tab1',
                            defaults: {
                                anchor: '100%',
                                margins: '0 0 10 0'
                            },
                            title: '고객현황',
                            tabConfig: {
                                xtype: 'tab',
                                listeners: {
                                    click: {
                                        fn: me.onCustomerTabClick,
                                        scope: me
                                    }
                                }
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    border: 0,
                                    height: 686,
                                    bodyPadding: '0 0 0 0',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: '',
                                            store: 'Customer.CustomerDataStore',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            text: '다시 읽기',
                                                            listeners: {
                                                                click: {
                                                                    fn: me.onButtonClick,
                                                                    scope: me
                                                                }
                                                            }
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'MyButton'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'MyButton'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'pagingtoolbar',
                                                    dock: 'bottom',
                                                    width: 360,
                                                    displayInfo: true,
                                                    store: 'Customer.CustomerDataStore'
                                                }
                                            ],
                                            viewConfig: {
                                                height: 212,
                                                maxHeight: 212,
                                                minHeight: 212,
                                                loadingText: '데이터를 불러오는 중...'
                                            },
                                            columns: [
                                                {
                                                    xtype: 'numbercolumn',
                                                    maxWidth: 60,
                                                    minWidth: 60,
                                                    width: 60,
                                                    align: 'right',
                                                    dataIndex: 'customernumber',
                                                    text: '고객번호',
                                                    format: '0000'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    maxWidth: 250,
                                                    minWidth: 250,
                                                    width: 250,
                                                    dataIndex: 'customername',
                                                    text: '고객명',
                                                    editor: {
                                                        xtype: 'textfield'
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    maxWidth: 180,
                                                    minWidth: 180,
                                                    width: 180,
                                                    dataIndex: 'phone',
                                                    text: '전화번호',
                                                    editor: {
                                                        xtype: 'textfield'
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    maxWidth: 110,
                                                    minWidth: 110,
                                                    width: 110,
                                                    dataIndex: 'country',
                                                    text: '국가'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    maxWidth: 90,
                                                    minWidth: 90,
                                                    width: 90,
                                                    dataIndex: 'state',
                                                    text: '주'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    maxWidth: 150,
                                                    minWidth: 150,
                                                    width: 150,
                                                    dataIndex: 'city',
                                                    text: '시'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    maxWidth: 100,
                                                    minWidth: 100,
                                                    width: 100,
                                                    align: 'right',
                                                    dataIndex: 'creditlimit',
                                                    text: '신용한도',
                                                    format: '0,000',
                                                    editor: {
                                                        xtype: 'numberfield'
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    maxWidth: 130,
                                                    minWidth: 130,
                                                    width: 130,
                                                    dataIndex: 'firstname',
                                                    text: '관리담당사원이름',
                                                    editor: {
                                                        xtype: 'combobox'
                                                    }
                                                }
                                            ],
                                            listeners: {
                                                selectionchange: {
                                                    fn: me.onGridpanelSelectionChange,
                                                    scope: me
                                                }
                                            },
                                            plugins: [
                                                Ext.create('Ext.grid.plugin.RowEditing', {

                                                })
                                            ]
                                        },
                                        {
                                            xtype: 'form',
                                            formBind: false,
                                            border: '0 0 0 0',
                                            frame: true,
                                            height: 259,
                                            id: 'customerform',
                                            autoScroll: true,
                                            defaults: {
                                                msgTarget: 'side',
                                                labelWidth: 75
                                            },
                                            bodyBorder: false,
                                            bodyPadding: '0 0 0 0',
                                            title: '고객 상세정보',
                                            waitTitle: '기다리십시오...',
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'bottom',
                                                    border: '',
                                                    id: 'buttons',
                                                    ui: 'footer',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            handler: function(button, e) {
                                                                try {
                                                                    Ext.Msg.show({
                                                                        title: '실행 확인',
                                                                        msg: '저장하시겠습니까?',
                                                                        buttons: Ext.Msg.YESNOCANCEL,
                                                                        icon: Ext.Msg.QUESTION
                                                                    });

                                                                    var form = this.up('form').getForm();
                                                                    form.submit({method: 'POST'});
                                                                } catch(ex) {
                                                                    var e = {
                                                                        type: 'js',
                                                                        message: ex.message,
                                                                        detail: 'JS 에러 유형: ' + ex.type + '<br/>\n' + '스택: ' + ex.stack
                                                                    };
                                                                    console.error(e);
                                                                    Ext.Msg.alert('에러 발생', ex.message + '<br/>\n\n' + ex.stack);
                                                                }
                                                            },
                                                            formBind: true,
                                                            border: true,
                                                            itemId: 'save',
                                                            width: 100,
                                                            iconCls: 'icon-save',
                                                            tabIndex: 1,
                                                            text: '저장'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            handler: function(button, e) {
                                                                this.up('form').getForm().reset();
                                                            },
                                                            formBind: true,
                                                            border: true,
                                                            width: 100,
                                                            iconCls: '',
                                                            tabIndex: 2,
                                                            text: '다시작성'
                                                        }
                                                    ]
                                                }
                                            ],
                                            items: [
                                                {
                                                    xtype: 'fieldset',
                                                    height: 71,
                                                    title: '고객 기본정보',
                                                    items: [
                                                        {
                                                            xtype: 'fieldcontainer',
                                                            height: 22,
                                                            layout: 'table',
                                                            fieldLabel: '고객기초정보',
                                                            items: [
                                                                {
                                                                    xtype: 'numberfield',
                                                                    maxWidth: 200,
                                                                    minWidth: 200,
                                                                    width: 200,
                                                                    afterLabelTextTpl: [
                                                                        '[',
                                                                        '    <span style="color:red;font-weight:bold" data-qtip="필수">*</span>',
                                                                        ']'
                                                                    ],
                                                                    fieldLabel: '고객번호',
                                                                    labelAlign: 'right',
                                                                    name: 'customernumber',
                                                                    allowDecimals: false,
                                                                    decimalPrecision: 0
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    maxWidth: 500,
                                                                    minWidth: 500,
                                                                    width: 500,
                                                                    afterLabelTextTpl: [
                                                                        '[',
                                                                        '    <span style="color:red;font-weight:bold" data-qtip="필수">*</span>',
                                                                        ']'
                                                                    ],
                                                                    fieldLabel: '고객명',
                                                                    labelAlign: 'right',
                                                                    name: 'customername',
                                                                    allowBlank: false
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    width: 266,
                                                                    afterLabelTextTpl: [
                                                                        '[',
                                                                        '    <span style="color:red;font-weight:bold" data-qtip="필수">*</span>',
                                                                        ']'
                                                                    ],
                                                                    fieldLabel: '전화번호',
                                                                    labelAlign: 'right',
                                                                    name: 'phone'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'fieldcontainer',
                                                            height: 23,
                                                            layout: 'table',
                                                            fieldLabel: '고객주소정보',
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    width: 400,
                                                                    fieldLabel: '국가',
                                                                    labelAlign: 'right',
                                                                    name: 'country'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    width: 300,
                                                                    fieldLabel: '주',
                                                                    labelAlign: 'right',
                                                                    name: 'state'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    width: 266,
                                                                    fieldLabel: '시',
                                                                    labelAlign: 'right',
                                                                    name: 'city'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldset',
                                                    title: '고객 신용정보',
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            anchor: '100%',
                                                            fieldLabel: '신용한도액',
                                                            labelAlign: 'right',
                                                            name: 'creditlimit'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'fieldset',
                                                    height: 48,
                                                    title: '관리담당 사원정보',
                                                    items: [
                                                        {
                                                            xtype: 'fieldcontainer',
                                                            height: 120,
                                                            layout: 'table',
                                                            fieldLabel: '',
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    fieldLabel: '관리담당사원번호',
                                                                    labelAlign: 'right',
                                                                    name: 'employeenumber'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    width: 713,
                                                                    fieldLabel: '관리담당사원이름',
                                                                    labelAlign: 'right',
                                                                    name: 'firstname'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'tab2',
                            title: 'Tab 2'
                        },
                        {
                            xtype: 'panel',
                            itemId: 'tab3',
                            title: 'Tab 3'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onCustomerTabClick: function(button, e, eOpts) {
        try {
            var tDataStore = Ext.StoreMgr.lookup('Customer.CustomerDataStore');
            tDataStore.load();
        } catch(ex) {
            var e = {
                type: 'js',
                message: ex.message,
                detail: 'JS 에러 유형: ' + ex.type + '<br/>\n' + '스택: ' + ex.stack
            };
            console.error(e);
            Ext.Msg.alert('에러 발생', ex.message + '<br/>\n\n' + ex.stack);
        }
    },

    onButtonClick: function(button, e, eOpts) {
        try {
            var tDataStore = Ext.StoreMgr.lookup('Customer.CustomerDataStore');
            tDataStore.load();
        } catch(ex) {
            var e = {
                type: 'js',
                message: ex.message,
                detail: 'JS 에러 유형: ' + ex.type + '<br/>\n' + '스택: ' + ex.stack
            };
            console.error(e);
            Ext.Msg.alert('에러 발생', ex.message + '<br/>\n\n' + ex.stack);
        }
    },

    onGridpanelSelectionChange: function(model, selected, eOpts) {
        var s = selected[0];
        if (s) {
          var form = Ext.getCmp('customerform');
          form.loadRecord(s);
        }

        //if (selected) {
            // Ext.Msg.show({title: '저장하시겠습니까?', msg: '하이고 순넘어 간다', buttons: Ext.Msg.YESNOCANCEL, icon: Ext.Msg.QUESTION });
          //  this.getForm().loadRecord(rec);
        //}

    }

});